#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Linq;
using System.Data.Linq.Mapping;
using System.Linq;
using System.Linq.Expressions;
using System.Reflection;



[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="MyDataBase")]
public partial class DataClassesDataContext : System.Data.Linq.DataContext
{
	
	private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
	
  #region 可扩展性方法定义
  partial void OnCreated();
  partial void InsertChuHuoMingDan(ChuHuoMingDan instance);
  partial void UpdateChuHuoMingDan(ChuHuoMingDan instance);
  partial void DeleteChuHuoMingDan(ChuHuoMingDan instance);
  partial void InsertFaHuoMingXi(FaHuoMingXi instance);
  partial void UpdateFaHuoMingXi(FaHuoMingXi instance);
  partial void DeleteFaHuoMingXi(FaHuoMingXi instance);
  partial void InsertYuShouKuan(YuShouKuan instance);
  partial void UpdateYuShouKuan(YuShouKuan instance);
  partial void DeleteYuShouKuan(YuShouKuan instance);
  #endregion
	
	public DataClassesDataContext() : 
			base(global::System.Configuration.ConfigurationManager.ConnectionStrings["MyDataBaseConnectionString"].ConnectionString, mappingSource)
	{
		OnCreated();
	}
	
	public DataClassesDataContext(string connection) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public DataClassesDataContext(System.Data.IDbConnection connection) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public DataClassesDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public DataClassesDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public System.Data.Linq.Table<ChuHuoMingDan> ChuHuoMingDan
	{
		get
		{
			return this.GetTable<ChuHuoMingDan>();
		}
	}
	
	public System.Data.Linq.Table<FaHuoMingXi> FaHuoMingXi
	{
		get
		{
			return this.GetTable<FaHuoMingXi>();
		}
	}
	
	public System.Data.Linq.Table<YuShouKuan> YuShouKuan
	{
		get
		{
			return this.GetTable<YuShouKuan>();
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ChuHuoMingDan")]
public partial class ChuHuoMingDan : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _ID;
	
	private System.Nullable<System.DateTime> _Date;
	
	private string _Grade;
	
	private System.Nullable<double> _Dia__外径_mm_;
	
	private System.Nullable<double> _ID_内径_mm_;
	
	private System.Nullable<double> _Thickness_厚度_mm_;
	
	private System.Nullable<double> _Quantity__pcs_;
	
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnDateChanging(System.Nullable<System.DateTime> value);
    partial void OnDateChanged();
    partial void OnGradeChanging(string value);
    partial void OnGradeChanged();
    partial void OnDia__外径_mm_Changing(System.Nullable<double> value);
    partial void OnDia__外径_mm_Changed();
    partial void OnID_内径_mm_Changing(System.Nullable<double> value);
    partial void OnID_内径_mm_Changed();
    partial void OnThickness_厚度_mm_Changing(System.Nullable<double> value);
    partial void OnThickness_厚度_mm_Changed();
    partial void OnQuantity__pcs_Changing(System.Nullable<double> value);
    partial void OnQuantity__pcs_Changed();
    #endregion
	
	public ChuHuoMingDan()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int ID
	{
		get
		{
			return this._ID;
		}
		set
		{
			if ((this._ID != value))
			{
				this.OnIDChanging(value);
				this.SendPropertyChanging();
				this._ID = value;
				this.SendPropertyChanged("ID");
				this.OnIDChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Date", DbType="DateTime")]
	public System.Nullable<System.DateTime> Date
	{
		get
		{
			return this._Date;
		}
		set
		{
			if ((this._Date != value))
			{
				this.OnDateChanging(value);
				this.SendPropertyChanging();
				this._Date = value;
				this.SendPropertyChanged("Date");
				this.OnDateChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Grade", DbType="NVarChar(255)")]
	public string Grade
	{
		get
		{
			return this._Grade;
		}
		set
		{
			if ((this._Grade != value))
			{
				this.OnGradeChanging(value);
				this.SendPropertyChanging();
				this._Grade = value;
				this.SendPropertyChanged("Grade");
				this.OnGradeChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Dia#_外径(mm)]", Storage="_Dia__外径_mm_", DbType="Float")]
	public System.Nullable<double> Dia__外径_mm_
	{
		get
		{
			return this._Dia__外径_mm_;
		}
		set
		{
			if ((this._Dia__外径_mm_ != value))
			{
				this.OnDia__外径_mm_Changing(value);
				this.SendPropertyChanging();
				this._Dia__外径_mm_ = value;
				this.SendPropertyChanged("Dia__外径_mm_");
				this.OnDia__外径_mm_Changed();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[ID_内径(mm)]", Storage="_ID_内径_mm_", DbType="Float")]
	public System.Nullable<double> ID_内径_mm_
	{
		get
		{
			return this._ID_内径_mm_;
		}
		set
		{
			if ((this._ID_内径_mm_ != value))
			{
				this.OnID_内径_mm_Changing(value);
				this.SendPropertyChanging();
				this._ID_内径_mm_ = value;
				this.SendPropertyChanged("ID_内径_mm_");
				this.OnID_内径_mm_Changed();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Thickness_厚度(mm)]", Storage="_Thickness_厚度_mm_", DbType="Float")]
	public System.Nullable<double> Thickness_厚度_mm_
	{
		get
		{
			return this._Thickness_厚度_mm_;
		}
		set
		{
			if ((this._Thickness_厚度_mm_ != value))
			{
				this.OnThickness_厚度_mm_Changing(value);
				this.SendPropertyChanging();
				this._Thickness_厚度_mm_ = value;
				this.SendPropertyChanged("Thickness_厚度_mm_");
				this.OnThickness_厚度_mm_Changed();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Quantity_(pcs)]", Storage="_Quantity__pcs_", DbType="Float")]
	public System.Nullable<double> Quantity__pcs_
	{
		get
		{
			return this._Quantity__pcs_;
		}
		set
		{
			if ((this._Quantity__pcs_ != value))
			{
				this.OnQuantity__pcs_Changing(value);
				this.SendPropertyChanging();
				this._Quantity__pcs_ = value;
				this.SendPropertyChanged("Quantity__pcs_");
				this.OnQuantity__pcs_Changed();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.FaHuoMingXi")]
public partial class FaHuoMingXi : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _ID;
	
	private System.Nullable<System.DateTime> _发货日期;
	
	private string _客户名;
	
	private string _牌号;
	
	private string _型号;
	
	private System.Nullable<double> _数量_件_;
	
	private System.Nullable<double> _单价_元_件_;
	
	private System.Nullable<double> _重量_kg_;
	
	private System.Nullable<double> _合计_元_;
	
	private string _备注;
	
	private System.Nullable<double> _订单金额;
	
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void On发货日期Changing(System.Nullable<System.DateTime> value);
    partial void On发货日期Changed();
    partial void On客户名Changing(string value);
    partial void On客户名Changed();
    partial void On牌号Changing(string value);
    partial void On牌号Changed();
    partial void On型号Changing(string value);
    partial void On型号Changed();
    partial void On数量_件_Changing(System.Nullable<double> value);
    partial void On数量_件_Changed();
    partial void On单价_元_件_Changing(System.Nullable<double> value);
    partial void On单价_元_件_Changed();
    partial void On重量_kg_Changing(System.Nullable<double> value);
    partial void On重量_kg_Changed();
    partial void On合计_元_Changing(System.Nullable<double> value);
    partial void On合计_元_Changed();
    partial void On备注Changing(string value);
    partial void On备注Changed();
    partial void On订单金额Changing(System.Nullable<double> value);
    partial void On订单金额Changed();
    #endregion
	
	public FaHuoMingXi()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int ID
	{
		get
		{
			return this._ID;
		}
		set
		{
			if ((this._ID != value))
			{
				this.OnIDChanging(value);
				this.SendPropertyChanging();
				this._ID = value;
				this.SendPropertyChanged("ID");
				this.OnIDChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_发货日期", DbType="DateTime")]
	public System.Nullable<System.DateTime> 发货日期
	{
		get
		{
			return this._发货日期;
		}
		set
		{
			if ((this._发货日期 != value))
			{
				this.On发货日期Changing(value);
				this.SendPropertyChanging();
				this._发货日期 = value;
				this.SendPropertyChanged("发货日期");
				this.On发货日期Changed();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_客户名", DbType="NVarChar(255)")]
	public string 客户名
	{
		get
		{
			return this._客户名;
		}
		set
		{
			if ((this._客户名 != value))
			{
				this.On客户名Changing(value);
				this.SendPropertyChanging();
				this._客户名 = value;
				this.SendPropertyChanged("客户名");
				this.On客户名Changed();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_牌号", DbType="NVarChar(255)")]
	public string 牌号
	{
		get
		{
			return this._牌号;
		}
		set
		{
			if ((this._牌号 != value))
			{
				this.On牌号Changing(value);
				this.SendPropertyChanging();
				this._牌号 = value;
				this.SendPropertyChanged("牌号");
				this.On牌号Changed();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_型号", DbType="NVarChar(255)")]
	public string 型号
	{
		get
		{
			return this._型号;
		}
		set
		{
			if ((this._型号 != value))
			{
				this.On型号Changing(value);
				this.SendPropertyChanging();
				this._型号 = value;
				this.SendPropertyChanged("型号");
				this.On型号Changed();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[数量(件）]", Storage="_数量_件_", DbType="Float")]
	public System.Nullable<double> 数量_件_
	{
		get
		{
			return this._数量_件_;
		}
		set
		{
			if ((this._数量_件_ != value))
			{
				this.On数量_件_Changing(value);
				this.SendPropertyChanging();
				this._数量_件_ = value;
				this.SendPropertyChanged("数量_件_");
				this.On数量_件_Changed();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[单价(元/件）]", Storage="_单价_元_件_", DbType="Float")]
	public System.Nullable<double> 单价_元_件_
	{
		get
		{
			return this._单价_元_件_;
		}
		set
		{
			if ((this._单价_元_件_ != value))
			{
				this.On单价_元_件_Changing(value);
				this.SendPropertyChanging();
				this._单价_元_件_ = value;
				this.SendPropertyChanged("单价_元_件_");
				this.On单价_元_件_Changed();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[重量（kg）]", Storage="_重量_kg_", DbType="Float")]
	public System.Nullable<double> 重量_kg_
	{
		get
		{
			return this._重量_kg_;
		}
		set
		{
			if ((this._重量_kg_ != value))
			{
				this.On重量_kg_Changing(value);
				this.SendPropertyChanging();
				this._重量_kg_ = value;
				this.SendPropertyChanged("重量_kg_");
				this.On重量_kg_Changed();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[合计（元）]", Storage="_合计_元_", DbType="Float")]
	public System.Nullable<double> 合计_元_
	{
		get
		{
			return this._合计_元_;
		}
		set
		{
			if ((this._合计_元_ != value))
			{
				this.On合计_元_Changing(value);
				this.SendPropertyChanging();
				this._合计_元_ = value;
				this.SendPropertyChanged("合计_元_");
				this.On合计_元_Changed();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_备注", DbType="NVarChar(255)")]
	public string 备注
	{
		get
		{
			return this._备注;
		}
		set
		{
			if ((this._备注 != value))
			{
				this.On备注Changing(value);
				this.SendPropertyChanging();
				this._备注 = value;
				this.SendPropertyChanged("备注");
				this.On备注Changed();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_订单金额", DbType="Float")]
	public System.Nullable<double> 订单金额
	{
		get
		{
			return this._订单金额;
		}
		set
		{
			if ((this._订单金额 != value))
			{
				this.On订单金额Changing(value);
				this.SendPropertyChanging();
				this._订单金额 = value;
				this.SendPropertyChanged("订单金额");
				this.On订单金额Changed();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.YuShouKuan")]
public partial class YuShouKuan : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _ID;
	
	private System.Nullable<System.DateTime> _日期;
	
	private string _所属公司;
	
	private System.Nullable<double> _金额;
	
	private string _收款人;
	
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void On日期Changing(System.Nullable<System.DateTime> value);
    partial void On日期Changed();
    partial void On所属公司Changing(string value);
    partial void On所属公司Changed();
    partial void On金额Changing(System.Nullable<double> value);
    partial void On金额Changed();
    partial void On收款人Changing(string value);
    partial void On收款人Changed();
    #endregion
	
	public YuShouKuan()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int ID
	{
		get
		{
			return this._ID;
		}
		set
		{
			if ((this._ID != value))
			{
				this.OnIDChanging(value);
				this.SendPropertyChanging();
				this._ID = value;
				this.SendPropertyChanged("ID");
				this.OnIDChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_日期", DbType="DateTime")]
	public System.Nullable<System.DateTime> 日期
	{
		get
		{
			return this._日期;
		}
		set
		{
			if ((this._日期 != value))
			{
				this.On日期Changing(value);
				this.SendPropertyChanging();
				this._日期 = value;
				this.SendPropertyChanged("日期");
				this.On日期Changed();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_所属公司", DbType="NVarChar(255)")]
	public string 所属公司
	{
		get
		{
			return this._所属公司;
		}
		set
		{
			if ((this._所属公司 != value))
			{
				this.On所属公司Changing(value);
				this.SendPropertyChanging();
				this._所属公司 = value;
				this.SendPropertyChanged("所属公司");
				this.On所属公司Changed();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_金额", DbType="Float")]
	public System.Nullable<double> 金额
	{
		get
		{
			return this._金额;
		}
		set
		{
			if ((this._金额 != value))
			{
				this.On金额Changing(value);
				this.SendPropertyChanging();
				this._金额 = value;
				this.SendPropertyChanged("金额");
				this.On金额Changed();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_收款人", DbType="NVarChar(255)")]
	public string 收款人
	{
		get
		{
			return this._收款人;
		}
		set
		{
			if ((this._收款人 != value))
			{
				this.On收款人Changing(value);
				this.SendPropertyChanging();
				this._收款人 = value;
				this.SendPropertyChanged("收款人");
				this.On收款人Changed();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}
#pragma warning restore 1591
